export const ALLOWED_PERMISSIONS = [
  { value: "CreateIncome", label: "CreateIncome" },
  { value: "UpdateIncome", label: "UpdateIncome" },
  { value: "DeleteIncome", label: "DeleteIncome" },
  { value: "CreateExpense", label: "CreateExpense" },
  { value: "UpdateExpense", label: "UpdateExpense" },
  { value: "DeleteExpense", label: "DeleteExpense" },
  { value: "CreateFinancialReport", label: "CreateFinancialReport" },
  { value: "UpdateFinancialReport", label: "UpdateFinancialReport" },
  { value: "DeleteFinancialReport", label: "DeleteFinancialReport" },
  { value: "CreateArusKas", label: "CreateArusKas" },
  { value: "UpdateArusKas", label: "UpdateArusKas" },
  { value: "DeleteArusKas", label: "DeleteArusKas" },
  { value: "CreateProgram", label: "CreateProgram" },
  { value: "UpdateProgram", label: "UpdateProgram" },
  { value: "DeleteProgram", label: "DeleteProgram" },
  { value: "CreateOperational", label: "CreateOperational" },
  { value: "UpdateOperational", label: "UpdateOperational" },
  { value: "DeleteOperational", label: "DeleteOperational" },
  { value: "ReadCOD", label: "ReadCOD" },
  { value: "CreateCOD", label: "CreateCOD" },
  { value: "UpdateCOD", label: "UpdateCOD" },
  { value: "DeleteCOD", label: "DeleteCOD" },
  { value: "CreateAttendeeManagement", label: "CreateAttendeeManagement" },
  { value: "UpdateAttendeeManagement", label: "UpdateAttendeeManagement" },
  { value: "DeleteAttendeeManagement", label: "DeleteAttendeeManagement" },
  { value: "CreateCheckIn", label: "CreateCheckIn" },
  { value: "UpdateCheckIn", label: "UpdateCheckIn" },
  { value: "DeleteCheckIn", label: "DeleteCheckIn" },
  { value: "CreateEventCreation", label: "CreateEventCreation" },
  { value: "UpdateEventCreation", label: "UpdateEventCreation" },
  { value: "DeleteEventCreation", label: "DeleteEventCreation" },
  { value: "CreateNotification", label: "CreateNotification" },
  { value: "UpdateNotification", label: "UpdateNotification" },
  { value: "DeleteNotification", label: "DeleteNotification" },
  { value: "CreateReport", label: "CreateReport" },
  { value: "UpdateReport", label: "UpdateReport" },
  { value: "DeleteReport", label: "DeleteReport" },
  { value: "CreateReview", label: "CreateReview" },
  { value: "UpdateReview", label: "UpdateReview" },
  { value: "DeleteReview", label: "DeleteReview" },
  { value: "CreateTypeEventCreation", label: "CreateTypeEventCreation" },
  { value: "UpdateTypeEventCreation", label: "UpdateTypeEventCreation" },
  { value: "DeleteTypeEventCreation", label: "DeleteTypeEventCreation" },
  { value: "CreateReviewAnonymous", label: "CreateReviewAnonymous" },
  { value: "UpdateReviewAnonymous", label: "UpdateReviewAnonymous" },
  { value: "DeleteReviewAnonymous", label: "DeleteReviewAnonymous" },
];

export const findAllowedPermission = (defaultValues) => {
  const defaultVal = ALLOWED_PERMISSIONS.filter((allowed) =>
    defaultValues.includes(allowed.value),
  );

  return defaultVal;
};
